### ISSUE TITLE
how to create the first user if CLI is not working 

### ISSUE THREAD

**Issue by fodkastir** [hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway#1]
Hi, thanks for posting this. Extremely helpful. I have gotten all service working and got stuck on creating the first user since the CLI is not working. Would you mind letting me know how did you create the first user? Thanks!

**Comment by hfte** [comment]
Thanks for your comment. Yes the tutorial is lacking some information there. I will fill this gap at the weekend. I did it with enabling signup in the .env file and set confirm to false there as well. And then I signed up in my browser using the netlify-identity-widget. And there the user was. Don't forget to set confirm to true afterwards. 

But there are other more elegant ways. I will document all of them.

**Comment by fodkastir** [comment]
@hfte Thanks so much for sharing this. Another question is, it seems you use nginx to redirect requests to identity/git-gateway to the local services. Is it possible to achieve the same effect by modifying the URLs in the implementation.js?
