### ISSUE TITLE
Redirect requests to the correct identity/git-gateway

### ISSUE THREAD

**Issue by hfte** [hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway#2]
@hfte Thanks so much for sharing this. Another question is, it seems you use nginx to redirect requests to identity/git-gateway to the local services. Is it possible to achieve the same effect by modifying the URLs in the implementation.js?  

By the way, would you mind sharing your .env file?

_Originally posted by @fodkastir in https://github.com/hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway/issues/1#issuecomment-452444948_

**Comment by hfte** [comment]
Why did someone want to do that? 

- For netlify cms you can set the gotrue and git-gateway URLs in it's config.yml file.

- For the identity widget you can use additional javascript like described here:
https://stackoverflow.com/questions/52174873/using-netlifys-hosted-identity-service-with-self-hosted-netlify-cms

**Comment by fodkastir** [comment]
@hfte I just found out I can do that in config.yml. Really appreciate your reply.
