### ISSUE TITLE
Troubleshooting "You don't have sufficient permissions to access Netlify CMS"

### ISSUE THREAD

**Issue by shawnmmatthews** [hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway#3]
Hey @hfte,

Thanks again for the detailed writeup! I'm running into a problem on running Gotrue, Git-gateway, and Gatsby all locally, and was wondering if you might provide some insight. I have Gotrue and Git-gatway both running (Gotrue is successfully writing to Mariadb and upon login Git-gateway is parsing a JWT claim) I'm running everything from https://localhost:8000 and have both login services proxied as follows via express... 

`developMiddleware: app => {
    app.use(
      '/.netlify/identity/',
      proxy({
        target:'http://localhost:8081',
        pathRewrite: {
          '/.netlify/identity/': '',
        },
      })
    )
    app.use(
      '/.netlify/git/',
      proxy({
        target:'http://localhost:9999',
        pathRewrite: {
          '/.netlify/git/': '',
        },
      })
    )
  },`

The site however is throwing an error stating that I don't have sufficient privileges. I'm not really sure if this is referring to the Github Token, Gotrue setup, or something I'm missing as part of the setup for Git-gateway. Do you have any suggestions on further troubleshooting options? I feel like I'm very close, and would love to get this working!

Thanks!

**Comment by hfte** [comment]
Sounds like you haven't properly configured roles.

Note that leaving the config in git-gateway empty won't lead to accepting all roles.

There's a trick for accepting all roles, I saw it in sone fork oft git-gateway.

**Comment by shawnmmatthews** [comment]
Well... I'm feeling foolish. That was it. I left the key in there with a blank value and hadn't thought to just remove the  GITGATEWAY_ROLES key all together. Thank you!!! This was an excellent initial writeup. I look forward to checking it out in a published form if you should decide to go forward with it. Thanks again!
